#ifndef _H_DIGITALVIDEO_RECEIVEFSM_SM
#define _H_DIGITALVIDEO_RECEIVEFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : DigitalVideo_ReceiveFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_environmentSensing_DigitalVideo_1_0
{
    // Forward declarations.
    class DigitalVideo_ReceiveFSM_SM;
    class DigitalVideo_ReceiveFSM_SM_Receiving_Ready_NotControlled;
    class DigitalVideo_ReceiveFSM_SM_Receiving_Ready_Controlled;
    class DigitalVideo_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class DigitalVideo_ReceiveFSM_SM_Default;
    class DigitalVideo_ReceiveFSMState;
    class DigitalVideo_ReceiveFSMContext;
    class DigitalVideo_ReceiveFSM;

    class DigitalVideo_ReceiveFSMState :
        public statemap::State
    {
    public:

        DigitalVideo_ReceiveFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(DigitalVideo_ReceiveFSMContext&) {};
        virtual void Exit(DigitalVideo_ReceiveFSMContext&) {};

        virtual void BroadcastGlobalTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void BroadcastLocalTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void CancelEventTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void ControlDigitalVideoSensorStreamTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void CreateEventTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void EventErrorTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void EventOccurredTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void InternalStateChange_To_DigitalVideo_ReceiveFSM_ReceivingTransition(DigitalVideo_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_ReadyTransition(DigitalVideo_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_Ready_ControlledTransition(DigitalVideo_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_Ready_NotControlledTransition(DigitalVideo_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void QueryAuthorityTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void QueryControlTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void QueryDigitalVideoSensorCapabilitiesTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void QueryDigitalVideoSensorConfigurationTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void QueryEventsTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void QuerySensorGeometricPropertiesTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void QueryTimeoutTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void QueryVisualSensorCapabilitiesTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void QueryVisualSensorConfigurationTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context, ControlDigitalVideoSensorStream msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context, QueryDigitalVideoSensorCapabilities msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context, QueryDigitalVideoSensorConfiguration msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context, SetDigitalVideoSensorConfiguration msg, Receive::Body::ReceiveRec transportData);
        virtual void ReleaseControlTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void RequestControlTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void SendTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void SetAuthorityTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void SetDigitalVideoSensorConfigurationTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void SetVisualSensorConfigurationTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void TimeoutTransition(DigitalVideo_ReceiveFSMContext& context);
        virtual void UpdateEventTransition(DigitalVideo_ReceiveFSMContext& context);

    protected:

        virtual void Default(DigitalVideo_ReceiveFSMContext& context);
    };

    class DigitalVideo_ReceiveFSM_SM
    {
    public:

        static DigitalVideo_ReceiveFSM_SM_Receiving_Ready_NotControlled Receiving_Ready_NotControlled;
        static DigitalVideo_ReceiveFSM_SM_Receiving_Ready_Controlled Receiving_Ready_Controlled;
        static DigitalVideo_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class DigitalVideo_ReceiveFSM_SM_Default :
        public DigitalVideo_ReceiveFSMState
    {
    public:

        DigitalVideo_ReceiveFSM_SM_Default(const char *name, int stateId)
        : DigitalVideo_ReceiveFSMState(name, stateId)
        {};

    };

    class DigitalVideo_ReceiveFSM_SM_Receiving_Ready_NotControlled :
        public DigitalVideo_ReceiveFSM_SM_Default
    {
    public:
        DigitalVideo_ReceiveFSM_SM_Receiving_Ready_NotControlled(const char *name, int stateId)
        : DigitalVideo_ReceiveFSM_SM_Default(name, stateId)
        {};

        void InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_Ready_ControlledTransition(DigitalVideo_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context, QueryDigitalVideoSensorCapabilities msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context, QueryDigitalVideoSensorConfiguration msg, Receive::Body::ReceiveRec transportData);
    };

    class DigitalVideo_ReceiveFSM_SM_Receiving_Ready_Controlled :
        public DigitalVideo_ReceiveFSM_SM_Default
    {
    public:
        DigitalVideo_ReceiveFSM_SM_Receiving_Ready_Controlled(const char *name, int stateId)
        : DigitalVideo_ReceiveFSM_SM_Default(name, stateId)
        {};

        void InternalStateChange_To_DigitalVideo_ReceiveFSM_ReceivingTransition(DigitalVideo_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_ReadyTransition(DigitalVideo_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_Ready_NotControlledTransition(DigitalVideo_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context, ControlDigitalVideoSensorStream msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context, QueryDigitalVideoSensorCapabilities msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context, QueryDigitalVideoSensorConfiguration msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context, SetDigitalVideoSensorConfiguration msg, Receive::Body::ReceiveRec transportData);
    };

    class DigitalVideo_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public DigitalVideo_ReceiveFSM_SM_Default
    {
    public:
        DigitalVideo_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : DigitalVideo_ReceiveFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(DigitalVideo_ReceiveFSMContext& context);
        void BroadcastLocalTransition(DigitalVideo_ReceiveFSMContext& context);
        void CancelEventTransition(DigitalVideo_ReceiveFSMContext& context);
        void ControlDigitalVideoSensorStreamTransition(DigitalVideo_ReceiveFSMContext& context);
        void CreateEventTransition(DigitalVideo_ReceiveFSMContext& context);
        void EventErrorTransition(DigitalVideo_ReceiveFSMContext& context);
        void EventOccurredTransition(DigitalVideo_ReceiveFSMContext& context);
        void QueryAuthorityTransition(DigitalVideo_ReceiveFSMContext& context);
        void QueryControlTransition(DigitalVideo_ReceiveFSMContext& context);
        void QueryDigitalVideoSensorCapabilitiesTransition(DigitalVideo_ReceiveFSMContext& context);
        void QueryDigitalVideoSensorConfigurationTransition(DigitalVideo_ReceiveFSMContext& context);
        void QueryEventsTransition(DigitalVideo_ReceiveFSMContext& context);
        void QuerySensorGeometricPropertiesTransition(DigitalVideo_ReceiveFSMContext& context);
        void QueryTimeoutTransition(DigitalVideo_ReceiveFSMContext& context);
        void QueryVisualSensorCapabilitiesTransition(DigitalVideo_ReceiveFSMContext& context);
        void QueryVisualSensorConfigurationTransition(DigitalVideo_ReceiveFSMContext& context);
        void ReceiveTransition(DigitalVideo_ReceiveFSMContext& context);
        void ReleaseControlTransition(DigitalVideo_ReceiveFSMContext& context);
        void RequestControlTransition(DigitalVideo_ReceiveFSMContext& context);
        void SendTransition(DigitalVideo_ReceiveFSMContext& context);
        void SetAuthorityTransition(DigitalVideo_ReceiveFSMContext& context);
        void SetDigitalVideoSensorConfigurationTransition(DigitalVideo_ReceiveFSMContext& context);
        void SetVisualSensorConfigurationTransition(DigitalVideo_ReceiveFSMContext& context);
        void TimeoutTransition(DigitalVideo_ReceiveFSMContext& context);
        void UpdateEventTransition(DigitalVideo_ReceiveFSMContext& context);
    };

    class DigitalVideo_ReceiveFSMContext :
        public statemap::FSMContext
    {
    public:

        DigitalVideo_ReceiveFSMContext(DigitalVideo_ReceiveFSM& owner)
        : FSMContext(DigitalVideo_ReceiveFSM_SM::Receiving_Ready_NotControlled),
          _owner(owner)
        {};

        DigitalVideo_ReceiveFSMContext(DigitalVideo_ReceiveFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        DigitalVideo_ReceiveFSM& getOwner() const
        {
            return (_owner);
        };

        DigitalVideo_ReceiveFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<DigitalVideo_ReceiveFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void ControlDigitalVideoSensorStreamTransition()
        {
            setTransition("ControlDigitalVideoSensorStreamTransition");
            (getState()).ControlDigitalVideoSensorStreamTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void InternalStateChange_To_DigitalVideo_ReceiveFSM_ReceivingTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_DigitalVideo_ReceiveFSM_ReceivingTransition");
            (getState()).InternalStateChange_To_DigitalVideo_ReceiveFSM_ReceivingTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_ReadyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_ReadyTransition");
            (getState()).InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_ReadyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_Ready_ControlledTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_Ready_ControlledTransition");
            (getState()).InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_Ready_ControlledTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_Ready_NotControlledTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_Ready_NotControlledTransition");
            (getState()).InternalStateChange_To_DigitalVideo_ReceiveFSM_Receiving_Ready_NotControlledTransition(*this, ie);
            setTransition(NULL);
        };

        void QueryAuthorityTransition()
        {
            setTransition("QueryAuthorityTransition");
            (getState()).QueryAuthorityTransition(*this);
            setTransition(NULL);
        };

        void QueryControlTransition()
        {
            setTransition("QueryControlTransition");
            (getState()).QueryControlTransition(*this);
            setTransition(NULL);
        };

        void QueryDigitalVideoSensorCapabilitiesTransition()
        {
            setTransition("QueryDigitalVideoSensorCapabilitiesTransition");
            (getState()).QueryDigitalVideoSensorCapabilitiesTransition(*this);
            setTransition(NULL);
        };

        void QueryDigitalVideoSensorConfigurationTransition()
        {
            setTransition("QueryDigitalVideoSensorConfigurationTransition");
            (getState()).QueryDigitalVideoSensorConfigurationTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void QuerySensorGeometricPropertiesTransition()
        {
            setTransition("QuerySensorGeometricPropertiesTransition");
            (getState()).QuerySensorGeometricPropertiesTransition(*this);
            setTransition(NULL);
        };

        void QueryTimeoutTransition()
        {
            setTransition("QueryTimeoutTransition");
            (getState()).QueryTimeoutTransition(*this);
            setTransition(NULL);
        };

        void QueryVisualSensorCapabilitiesTransition()
        {
            setTransition("QueryVisualSensorCapabilitiesTransition");
            (getState()).QueryVisualSensorCapabilitiesTransition(*this);
            setTransition(NULL);
        };

        void QueryVisualSensorConfigurationTransition()
        {
            setTransition("QueryVisualSensorConfigurationTransition");
            (getState()).QueryVisualSensorConfigurationTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition(ControlDigitalVideoSensorStream msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(QueryDigitalVideoSensorCapabilities msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(QueryDigitalVideoSensorConfiguration msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(SetDigitalVideoSensorConfiguration msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReleaseControlTransition()
        {
            setTransition("ReleaseControlTransition");
            (getState()).ReleaseControlTransition(*this);
            setTransition(NULL);
        };

        void RequestControlTransition()
        {
            setTransition("RequestControlTransition");
            (getState()).RequestControlTransition(*this);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void SetAuthorityTransition()
        {
            setTransition("SetAuthorityTransition");
            (getState()).SetAuthorityTransition(*this);
            setTransition(NULL);
        };

        void SetDigitalVideoSensorConfigurationTransition()
        {
            setTransition("SetDigitalVideoSensorConfigurationTransition");
            (getState()).SetDigitalVideoSensorConfigurationTransition(*this);
            setTransition(NULL);
        };

        void SetVisualSensorConfigurationTransition()
        {
            setTransition("SetVisualSensorConfigurationTransition");
            (getState()).SetVisualSensorConfigurationTransition(*this);
            setTransition(NULL);
        };

        void TimeoutTransition()
        {
            setTransition("TimeoutTransition");
            (getState()).TimeoutTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        DigitalVideo_ReceiveFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_DIGITALVIDEO_RECEIVEFSM_SM
