#ifndef _H_LOCALVECTORDRIVER_SENDFSM_SM
#define _H_LOCALVECTORDRIVER_SENDFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : LocalVectorDriver_SendFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_mobility_LocalVectorDriver_1_0
{
    // Forward declarations.
    class LocalVectorDriver_SendFSM_SM;
    class LocalVectorDriver_SendFSM_SM_Sending;
    class LocalVectorDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class LocalVectorDriver_SendFSM_SM_Default;
    class LocalVectorDriver_SendFSMState;
    class LocalVectorDriver_SendFSMContext;
    class LocalVectorDriver_SendFSM;

    class LocalVectorDriver_SendFSMState :
        public statemap::State
    {
    public:

        LocalVectorDriver_SendFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(LocalVectorDriver_SendFSMContext&) {};
        virtual void Exit(LocalVectorDriver_SendFSMContext&) {};

        virtual void BroadcastGlobalTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void BroadcastLocalTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void CancelEventTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void ClearEmergencyTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void CreateEventTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void EventErrorTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void EventOccurredTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void FailureTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void InitializedTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void QueryAuthorityTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void QueryControlTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void QueryEventsTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void QueryLocalVectorTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void QueryStatusTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void QueryTimeoutTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void ReceiveTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void ReleaseControlTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void RequestControlTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void ResetTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void ResumeTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void SendTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void SetAuthorityTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void SetEmergencyTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void SetLocalVectorTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void ShutdownTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void StandbyTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void TimeoutTransition(LocalVectorDriver_SendFSMContext& context);
        virtual void UpdateEventTransition(LocalVectorDriver_SendFSMContext& context);

    protected:

        virtual void Default(LocalVectorDriver_SendFSMContext& context);
    };

    class LocalVectorDriver_SendFSM_SM
    {
    public:

        static LocalVectorDriver_SendFSM_SM_Sending Sending;
        static LocalVectorDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class LocalVectorDriver_SendFSM_SM_Default :
        public LocalVectorDriver_SendFSMState
    {
    public:

        LocalVectorDriver_SendFSM_SM_Default(const char *name, int stateId)
        : LocalVectorDriver_SendFSMState(name, stateId)
        {};

    };

    class LocalVectorDriver_SendFSM_SM_Sending :
        public LocalVectorDriver_SendFSM_SM_Default
    {
    public:
        LocalVectorDriver_SendFSM_SM_Sending(const char *name, int stateId)
        : LocalVectorDriver_SendFSM_SM_Default(name, stateId)
        {};

    };

    class LocalVectorDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public LocalVectorDriver_SendFSM_SM_Default
    {
    public:
        LocalVectorDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : LocalVectorDriver_SendFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(LocalVectorDriver_SendFSMContext& context);
        void BroadcastLocalTransition(LocalVectorDriver_SendFSMContext& context);
        void CancelEventTransition(LocalVectorDriver_SendFSMContext& context);
        void ClearEmergencyTransition(LocalVectorDriver_SendFSMContext& context);
        void CreateEventTransition(LocalVectorDriver_SendFSMContext& context);
        void EventErrorTransition(LocalVectorDriver_SendFSMContext& context);
        void EventOccurredTransition(LocalVectorDriver_SendFSMContext& context);
        void FailureTransition(LocalVectorDriver_SendFSMContext& context);
        void InitializedTransition(LocalVectorDriver_SendFSMContext& context);
        void QueryAuthorityTransition(LocalVectorDriver_SendFSMContext& context);
        void QueryControlTransition(LocalVectorDriver_SendFSMContext& context);
        void QueryEventsTransition(LocalVectorDriver_SendFSMContext& context);
        void QueryLocalVectorTransition(LocalVectorDriver_SendFSMContext& context);
        void QueryStatusTransition(LocalVectorDriver_SendFSMContext& context);
        void QueryTimeoutTransition(LocalVectorDriver_SendFSMContext& context);
        void ReceiveTransition(LocalVectorDriver_SendFSMContext& context);
        void ReleaseControlTransition(LocalVectorDriver_SendFSMContext& context);
        void RequestControlTransition(LocalVectorDriver_SendFSMContext& context);
        void ResetTransition(LocalVectorDriver_SendFSMContext& context);
        void ResumeTransition(LocalVectorDriver_SendFSMContext& context);
        void SendTransition(LocalVectorDriver_SendFSMContext& context);
        void SetAuthorityTransition(LocalVectorDriver_SendFSMContext& context);
        void SetEmergencyTransition(LocalVectorDriver_SendFSMContext& context);
        void SetLocalVectorTransition(LocalVectorDriver_SendFSMContext& context);
        void ShutdownTransition(LocalVectorDriver_SendFSMContext& context);
        void StandbyTransition(LocalVectorDriver_SendFSMContext& context);
        void TimeoutTransition(LocalVectorDriver_SendFSMContext& context);
        void UpdateEventTransition(LocalVectorDriver_SendFSMContext& context);
    };

    class LocalVectorDriver_SendFSMContext :
        public statemap::FSMContext
    {
    public:

        LocalVectorDriver_SendFSMContext(LocalVectorDriver_SendFSM& owner)
        : FSMContext(LocalVectorDriver_SendFSM_SM::Sending),
          _owner(owner)
        {};

        LocalVectorDriver_SendFSMContext(LocalVectorDriver_SendFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        LocalVectorDriver_SendFSM& getOwner() const
        {
            return (_owner);
        };

        LocalVectorDriver_SendFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<LocalVectorDriver_SendFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void ClearEmergencyTransition()
        {
            setTransition("ClearEmergencyTransition");
            (getState()).ClearEmergencyTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void FailureTransition()
        {
            setTransition("FailureTransition");
            (getState()).FailureTransition(*this);
            setTransition(NULL);
        };

        void InitializedTransition()
        {
            setTransition("InitializedTransition");
            (getState()).InitializedTransition(*this);
            setTransition(NULL);
        };

        void QueryAuthorityTransition()
        {
            setTransition("QueryAuthorityTransition");
            (getState()).QueryAuthorityTransition(*this);
            setTransition(NULL);
        };

        void QueryControlTransition()
        {
            setTransition("QueryControlTransition");
            (getState()).QueryControlTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void QueryLocalVectorTransition()
        {
            setTransition("QueryLocalVectorTransition");
            (getState()).QueryLocalVectorTransition(*this);
            setTransition(NULL);
        };

        void QueryStatusTransition()
        {
            setTransition("QueryStatusTransition");
            (getState()).QueryStatusTransition(*this);
            setTransition(NULL);
        };

        void QueryTimeoutTransition()
        {
            setTransition("QueryTimeoutTransition");
            (getState()).QueryTimeoutTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void ReleaseControlTransition()
        {
            setTransition("ReleaseControlTransition");
            (getState()).ReleaseControlTransition(*this);
            setTransition(NULL);
        };

        void RequestControlTransition()
        {
            setTransition("RequestControlTransition");
            (getState()).RequestControlTransition(*this);
            setTransition(NULL);
        };

        void ResetTransition()
        {
            setTransition("ResetTransition");
            (getState()).ResetTransition(*this);
            setTransition(NULL);
        };

        void ResumeTransition()
        {
            setTransition("ResumeTransition");
            (getState()).ResumeTransition(*this);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void SetAuthorityTransition()
        {
            setTransition("SetAuthorityTransition");
            (getState()).SetAuthorityTransition(*this);
            setTransition(NULL);
        };

        void SetEmergencyTransition()
        {
            setTransition("SetEmergencyTransition");
            (getState()).SetEmergencyTransition(*this);
            setTransition(NULL);
        };

        void SetLocalVectorTransition()
        {
            setTransition("SetLocalVectorTransition");
            (getState()).SetLocalVectorTransition(*this);
            setTransition(NULL);
        };

        void ShutdownTransition()
        {
            setTransition("ShutdownTransition");
            (getState()).ShutdownTransition(*this);
            setTransition(NULL);
        };

        void StandbyTransition()
        {
            setTransition("StandbyTransition");
            (getState()).StandbyTransition(*this);
            setTransition(NULL);
        };

        void TimeoutTransition()
        {
            setTransition("TimeoutTransition");
            (getState()).TimeoutTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        LocalVectorDriver_SendFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_LOCALVECTORDRIVER_SENDFSM_SM
