#ifndef URN_JAUS_JSS_MOBILITY_ACCELERATIONSTATESENSOR_0_6_INTERNALEVENTSSET
#define URN_JAUS_JSS_MOBILITY_ACCELERATIONSTATESENSOR_0_6_INTERNALEVENTSSET

#include "EventError.h"
#include "BroadcastGlobal.h"
#include "BroadcastLocal.h"
#include "EventOccurred.h"

#endif //URN_JAUS_JSS_MOBILITY_ACCELERATIONSTATESENSOR_0_6_INTERNALEVENTSSET
