find_path(LIBJAUS_INCLUDE_DIRS JConstants.h /usr/include "$ENV{NAMER_ROOT}")

find_library(LIBJAUS_LIBRARIES JAUS_common /usr/lib "$ENV{NAMER_ROOT}")

set(LIBJAUS_FOUND TRUE)

if (NOT LIBJAUS_INCLUDE_DIRS)
    set(LIBJAUS_FOUND FALSE)
endif (NOT LIBJAUS_INCLUDE_DIRS)

if (NOT LIBJAUS_LIBRARIES)
    set(LIBJAUS_FOUND FALSE)
endif (NOT LIBJAUS_LIBRARIES)
