/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AccelerationStateSensor_SendFSM_sm.sm
 */

#include "urn_jaus_jss_mobility_AccelerationStateSensor_0_6/Messages/MessageSet.h"
#include "urn_jaus_jss_mobility_AccelerationStateSensor_0_6/AccelerationStateSensor_SendFSM.h"
#include "include/urn_jaus_jss_mobility_AccelerationStateSensor_0_6/AccelerationStateSensor_SendFSM_sm.h"

using namespace statemap;

namespace urn_jaus_jss_mobility_AccelerationStateSensor_0_6
{
    // Static class declarations.
    AccelerationStateSensor_SendFSM_SM_Sending AccelerationStateSensor_SendFSM_SM::Sending("AccelerationStateSensor_SendFSM_SM::Sending", 0);
    AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE("AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE", 1);

    void AccelerationStateSensor_SendFSMState::BroadcastGlobalTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::BroadcastLocalTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::CancelEventTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::CreateEventTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::EventErrorTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::EventOccurredTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::QueryAccelerationStateTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::QueryEventsTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::ReceiveTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::SendTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::UpdateEventTransition(AccelerationStateSensor_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_SendFSMState::Default(AccelerationStateSensor_SendFSMContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CancelEventTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CreateEventTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::EventErrorTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::EventOccurredTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryAccelerationStateTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryAccelerationStateTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryAccelerationStateTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryEventsTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ReceiveTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SendTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::UpdateEventTransition(AccelerationStateSensor_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
