/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AccelerationStateSensor_ReceiveFSM_sm.sm
 */

#include "urn_jaus_jss_mobility_AccelerationStateSensor_0_6/Messages/MessageSet.h"
#include "urn_jaus_jss_mobility_AccelerationStateSensor_0_6/AccelerationStateSensor_ReceiveFSM.h"
#include "include/urn_jaus_jss_mobility_AccelerationStateSensor_0_6/AccelerationStateSensor_ReceiveFSM_sm.h"

using namespace statemap;

namespace urn_jaus_jss_mobility_AccelerationStateSensor_0_6
{
    // Static class declarations.
    AccelerationStateSensor_ReceiveFSM_SM_Receiving_Ready AccelerationStateSensor_ReceiveFSM_SM::Receiving_Ready("AccelerationStateSensor_ReceiveFSM_SM::Receiving_Ready", 0);
    AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE("AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE", 1);

    void AccelerationStateSensor_ReceiveFSMState::BroadcastGlobalTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::BroadcastLocalTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::CancelEventTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::CreateEventTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::EventErrorTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::EventOccurredTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::QueryAccelerationStateTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::QueryEventsTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::ReceiveTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::ReceiveTransition(AccelerationStateSensor_ReceiveFSMContext& context, QueryAccelerationState msg, Receive::Body::ReceiveRec transportData)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::SendTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::UpdateEventTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void AccelerationStateSensor_ReceiveFSMState::Default(AccelerationStateSensor_ReceiveFSMContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Receiving_Ready::ReceiveTransition(AccelerationStateSensor_ReceiveFSMContext& context, QueryAccelerationState msg, Receive::Body::ReceiveRec transportData)
    {
        AccelerationStateSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Receiving_Ready"
            << std::endl;
        }

        AccelerationStateSensor_ReceiveFSMState& endState = context.getState();

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Receiving_Ready::ReceiveTransition(QueryAccelerationState msg, Receive::Body::ReceiveRec transportData)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.SendAction("ReportAccelerationState", transportData);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Receiving_Ready::ReceiveTransition(QueryAccelerationState msg, Receive::Body::ReceiveRec transportData)"
                    << std::endl;
            }

            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::CancelEventTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::CreateEventTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::EventErrorTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::EventOccurredTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryAccelerationStateTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryAccelerationStateTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryAccelerationStateTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryEventsTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::ReceiveTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::SendTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }


        return;
    }

    void AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::UpdateEventTransition(AccelerationStateSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : AccelerationStateSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
