#ifndef _H_PRIMITIVEDRIVER_RECEIVEFSM_SM
#define _H_PRIMITIVEDRIVER_RECEIVEFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : PrimitiveDriver_ReceiveFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_mobility_PrimitiveDriver_1_0
{
    // Forward declarations.
    class PrimitiveDriver_ReceiveFSM_SM;
    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Standby;
    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Init;
    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Failure;
    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Shutdown;
    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Emergency;
    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Standby;
    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Ready;
    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Emergency;
    class PrimitiveDriver_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class PrimitiveDriver_ReceiveFSM_SM_Default;
    class PrimitiveDriver_ReceiveFSMState;
    class PrimitiveDriver_ReceiveFSMContext;
    class PrimitiveDriver_ReceiveFSM;

    class PrimitiveDriver_ReceiveFSMState :
        public statemap::State
    {
    public:

        PrimitiveDriver_ReceiveFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(PrimitiveDriver_ReceiveFSMContext&) {};
        virtual void Exit(PrimitiveDriver_ReceiveFSMContext&) {};

        virtual void BroadcastGlobalTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void BroadcastLocalTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void CancelEventTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void ClearEmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void CreateEventTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void EventErrorTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void EventOccurredTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void FailureTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void InitializedTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        virtual void QueryAuthorityTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void QueryControlTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void QueryEventsTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void QueryStatusTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void QueryTimeoutTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void QueryWrenchEffortTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, QueryWrenchEffort msg, Receive::Body::ReceiveRec transportData);
        virtual void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, SetWrenchEffort msg, Receive::Body::ReceiveRec transportData);
        virtual void ReleaseControlTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void RequestControlTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void ResetTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void ResumeTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void SendTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void SetAuthorityTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void SetEmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void SetWrenchEffortTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void ShutdownTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void TimeoutTransition(PrimitiveDriver_ReceiveFSMContext& context);
        virtual void UpdateEventTransition(PrimitiveDriver_ReceiveFSMContext& context);

    protected:

        virtual void Default(PrimitiveDriver_ReceiveFSMContext& context);
    };

    class PrimitiveDriver_ReceiveFSM_SM
    {
    public:

        static PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Standby Receiving_Ready_NotControlled_StateA_Standby;
        static PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Init Receiving_Ready_NotControlled_StateA_Init;
        static PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Failure Receiving_Ready_NotControlled_StateA_Failure;
        static PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Shutdown Receiving_Ready_NotControlled_StateA_Shutdown;
        static PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Emergency Receiving_Ready_NotControlled_StateA_Emergency;
        static PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Standby Receiving_Ready_Controlled_StateB_Standby;
        static PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Ready Receiving_Ready_Controlled_StateB_Ready;
        static PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Emergency Receiving_Ready_Controlled_StateB_Emergency;
        static PrimitiveDriver_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class PrimitiveDriver_ReceiveFSM_SM_Default :
        public PrimitiveDriver_ReceiveFSMState
    {
    public:

        PrimitiveDriver_ReceiveFSM_SM_Default(const char *name, int stateId)
        : PrimitiveDriver_ReceiveFSMState(name, stateId)
        {};

    };

    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Standby :
        public PrimitiveDriver_ReceiveFSM_SM_Default
    {
    public:
        PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Standby(const char *name, int stateId)
        : PrimitiveDriver_ReceiveFSM_SM_Default(name, stateId)
        {};

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, QueryWrenchEffort msg, Receive::Body::ReceiveRec transportData);
    };

    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Init :
        public PrimitiveDriver_ReceiveFSM_SM_Default
    {
    public:
        PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Init(const char *name, int stateId)
        : PrimitiveDriver_ReceiveFSM_SM_Default(name, stateId)
        {};

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, QueryWrenchEffort msg, Receive::Body::ReceiveRec transportData);
    };

    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Failure :
        public PrimitiveDriver_ReceiveFSM_SM_Default
    {
    public:
        PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Failure(const char *name, int stateId)
        : PrimitiveDriver_ReceiveFSM_SM_Default(name, stateId)
        {};

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, QueryWrenchEffort msg, Receive::Body::ReceiveRec transportData);
    };

    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Shutdown :
        public PrimitiveDriver_ReceiveFSM_SM_Default
    {
    public:
        PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Shutdown(const char *name, int stateId)
        : PrimitiveDriver_ReceiveFSM_SM_Default(name, stateId)
        {};

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, QueryWrenchEffort msg, Receive::Body::ReceiveRec transportData);
    };

    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Emergency :
        public PrimitiveDriver_ReceiveFSM_SM_Default
    {
    public:
        PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_NotControlled_StateA_Emergency(const char *name, int stateId)
        : PrimitiveDriver_ReceiveFSM_SM_Default(name, stateId)
        {};

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, QueryWrenchEffort msg, Receive::Body::ReceiveRec transportData);
    };

    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Standby :
        public PrimitiveDriver_ReceiveFSM_SM_Default
    {
    public:
        PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Standby(const char *name, int stateId)
        : PrimitiveDriver_ReceiveFSM_SM_Default(name, stateId)
        {};

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, QueryWrenchEffort msg, Receive::Body::ReceiveRec transportData);
    };

    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Ready :
        public PrimitiveDriver_ReceiveFSM_SM_Default
    {
    public:
        PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Ready(const char *name, int stateId)
        : PrimitiveDriver_ReceiveFSM_SM_Default(name, stateId)
        {};

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, QueryWrenchEffort msg, Receive::Body::ReceiveRec transportData);
        void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, SetWrenchEffort msg, Receive::Body::ReceiveRec transportData);
    };

    class PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Emergency :
        public PrimitiveDriver_ReceiveFSM_SM_Default
    {
    public:
        PrimitiveDriver_ReceiveFSM_SM_Receiving_Ready_Controlled_StateB_Emergency(const char *name, int stateId)
        : PrimitiveDriver_ReceiveFSM_SM_Default(name, stateId)
        {};

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context, JTS::InternalEvent* ie);
        void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context, QueryWrenchEffort msg, Receive::Body::ReceiveRec transportData);
    };

    class PrimitiveDriver_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public PrimitiveDriver_ReceiveFSM_SM_Default
    {
    public:
        PrimitiveDriver_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : PrimitiveDriver_ReceiveFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void BroadcastLocalTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void CancelEventTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void ClearEmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void CreateEventTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void EventErrorTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void EventOccurredTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void FailureTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void InitializedTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void QueryAuthorityTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void QueryControlTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void QueryEventsTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void QueryStatusTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void QueryTimeoutTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void QueryWrenchEffortTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void ReceiveTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void ReleaseControlTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void RequestControlTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void ResetTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void ResumeTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void SendTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void SetAuthorityTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void SetEmergencyTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void SetWrenchEffortTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void ShutdownTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void StandbyTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void TimeoutTransition(PrimitiveDriver_ReceiveFSMContext& context);
        void UpdateEventTransition(PrimitiveDriver_ReceiveFSMContext& context);
    };

    class PrimitiveDriver_ReceiveFSMContext :
        public statemap::FSMContext
    {
    public:

        PrimitiveDriver_ReceiveFSMContext(PrimitiveDriver_ReceiveFSM& owner)
        : FSMContext(PrimitiveDriver_ReceiveFSM_SM::Receiving_Ready_NotControlled_StateA_Init),
          _owner(owner)
        {};

        PrimitiveDriver_ReceiveFSMContext(PrimitiveDriver_ReceiveFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        PrimitiveDriver_ReceiveFSM& getOwner() const
        {
            return (_owner);
        };

        PrimitiveDriver_ReceiveFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<PrimitiveDriver_ReceiveFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void ClearEmergencyTransition()
        {
            setTransition("ClearEmergencyTransition");
            (getState()).ClearEmergencyTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void FailureTransition()
        {
            setTransition("FailureTransition");
            (getState()).FailureTransition(*this);
            setTransition(NULL);
        };

        void InitializedTransition()
        {
            setTransition("InitializedTransition");
            (getState()).InitializedTransition(*this);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_ReceivingTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_ReadyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_ControlledTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateBTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_EmergencyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_ReadyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_Controlled_StateB_StandbyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlledTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateATransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_EmergencyTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_FailureTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_InitTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_ShutdownTransition(*this, ie);
            setTransition(NULL);
        };

        void InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(JTS::InternalEvent* ie)
        {
            setTransition("InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition");
            (getState()).InternalStateChange_To_PrimitiveDriver_ReceiveFSM_Receiving_Ready_NotControlled_StateA_StandbyTransition(*this, ie);
            setTransition(NULL);
        };

        void QueryAuthorityTransition()
        {
            setTransition("QueryAuthorityTransition");
            (getState()).QueryAuthorityTransition(*this);
            setTransition(NULL);
        };

        void QueryControlTransition()
        {
            setTransition("QueryControlTransition");
            (getState()).QueryControlTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void QueryStatusTransition()
        {
            setTransition("QueryStatusTransition");
            (getState()).QueryStatusTransition(*this);
            setTransition(NULL);
        };

        void QueryTimeoutTransition()
        {
            setTransition("QueryTimeoutTransition");
            (getState()).QueryTimeoutTransition(*this);
            setTransition(NULL);
        };

        void QueryWrenchEffortTransition()
        {
            setTransition("QueryWrenchEffortTransition");
            (getState()).QueryWrenchEffortTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition(QueryWrenchEffort msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReceiveTransition(SetWrenchEffort msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void ReleaseControlTransition()
        {
            setTransition("ReleaseControlTransition");
            (getState()).ReleaseControlTransition(*this);
            setTransition(NULL);
        };

        void RequestControlTransition()
        {
            setTransition("RequestControlTransition");
            (getState()).RequestControlTransition(*this);
            setTransition(NULL);
        };

        void ResetTransition()
        {
            setTransition("ResetTransition");
            (getState()).ResetTransition(*this);
            setTransition(NULL);
        };

        void ResumeTransition()
        {
            setTransition("ResumeTransition");
            (getState()).ResumeTransition(*this);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void SetAuthorityTransition()
        {
            setTransition("SetAuthorityTransition");
            (getState()).SetAuthorityTransition(*this);
            setTransition(NULL);
        };

        void SetEmergencyTransition()
        {
            setTransition("SetEmergencyTransition");
            (getState()).SetEmergencyTransition(*this);
            setTransition(NULL);
        };

        void SetWrenchEffortTransition()
        {
            setTransition("SetWrenchEffortTransition");
            (getState()).SetWrenchEffortTransition(*this);
            setTransition(NULL);
        };

        void ShutdownTransition()
        {
            setTransition("ShutdownTransition");
            (getState()).ShutdownTransition(*this);
            setTransition(NULL);
        };

        void StandbyTransition()
        {
            setTransition("StandbyTransition");
            (getState()).StandbyTransition(*this);
            setTransition(NULL);
        };

        void TimeoutTransition()
        {
            setTransition("TimeoutTransition");
            (getState()).TimeoutTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        PrimitiveDriver_ReceiveFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_PRIMITIVEDRIVER_RECEIVEFSM_SM
