/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : PrimitiveDriver_SendFSM_sm.sm
 */

#include "urn_jaus_jss_mobility_PrimitiveDriver_1_0/Messages/MessageSet.h"
#include "urn_jaus_jss_mobility_PrimitiveDriver_1_0/PrimitiveDriver_SendFSM.h"
#include "include/urn_jaus_jss_mobility_PrimitiveDriver_1_0/PrimitiveDriver_SendFSM_sm.h"

using namespace statemap;

namespace urn_jaus_jss_mobility_PrimitiveDriver_1_0
{
    // Static class declarations.
    PrimitiveDriver_SendFSM_SM_Sending PrimitiveDriver_SendFSM_SM::Sending("PrimitiveDriver_SendFSM_SM::Sending", 0);
    PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE("PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE", 1);

    void PrimitiveDriver_SendFSMState::BroadcastGlobalTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::BroadcastLocalTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::CancelEventTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::ClearEmergencyTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::CreateEventTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::EventErrorTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::EventOccurredTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::FailureTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::InitializedTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::QueryAuthorityTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::QueryControlTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::QueryEventsTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::QueryStatusTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::QueryTimeoutTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::QueryWrenchEffortTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::ReceiveTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::ReleaseControlTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::RequestControlTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::ResetTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::ResumeTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::SendTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::SetAuthorityTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::SetEmergencyTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::SetWrenchEffortTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::ShutdownTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::StandbyTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::TimeoutTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::UpdateEventTransition(PrimitiveDriver_SendFSMContext& context)
    {
        Default(context);
        return;
    }

    void PrimitiveDriver_SendFSMState::Default(PrimitiveDriver_SendFSMContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CancelEventTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ClearEmergencyTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ClearEmergencyTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ClearEmergencyTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::CreateEventTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::EventErrorTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::EventOccurredTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::FailureTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::FailureTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::FailureTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::InitializedTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::InitializedTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::InitializedTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryAuthorityTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryAuthorityTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryAuthorityTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryControlTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryControlTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryControlTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryEventsTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryStatusTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryStatusTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryStatusTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryTimeoutTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryTimeoutTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryTimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryWrenchEffortTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryWrenchEffortTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryWrenchEffortTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ReceiveTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ReleaseControlTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReleaseControlTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ReleaseControlTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::RequestControlTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::RequestControlTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::RequestControlTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ResetTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ResetTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ResetTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ResumeTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ResumeTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ResumeTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SendTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SetAuthorityTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetAuthorityTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetAuthorityTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SetEmergencyTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetEmergencyTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetEmergencyTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::SetWrenchEffortTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetWrenchEffortTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::SetWrenchEffortTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::ShutdownTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ShutdownTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::ShutdownTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::StandbyTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::StandbyTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::StandbyTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::TimeoutTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::TimeoutTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::TimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void PrimitiveDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE::UpdateEventTransition(PrimitiveDriver_SendFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : PrimitiveDriver_SendFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
