/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : GlobalPoseSensor_ReceiveFSM_sm.sm
 */

#include "urn_jaus_jss_mobility_GlobalPoseSensor_1_0/Messages/MessageSet.h"
#include "urn_jaus_jss_mobility_GlobalPoseSensor_1_0/GlobalPoseSensor_ReceiveFSM.h"
#include "include/urn_jaus_jss_mobility_GlobalPoseSensor_1_0/GlobalPoseSensor_ReceiveFSM_sm.h"

using namespace statemap;

namespace urn_jaus_jss_mobility_GlobalPoseSensor_1_0
{
    // Static class declarations.
    GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_NotControlled GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled("GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled", 0);
    GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled("GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled", 1);
    GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE("GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE", 2);

    void GlobalPoseSensor_ReceiveFSMState::BroadcastGlobalTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::BroadcastLocalTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::CancelEventTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::CreateEventTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::EventErrorTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::EventOccurredTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_ReceivingTransition(GlobalPoseSensor_ReceiveFSMContext& context, JTS::InternalEvent* ie)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_ReadyTransition(GlobalPoseSensor_ReceiveFSMContext& context, JTS::InternalEvent* ie)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition(GlobalPoseSensor_ReceiveFSMContext& context, JTS::InternalEvent* ie)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition(GlobalPoseSensor_ReceiveFSMContext& context, JTS::InternalEvent* ie)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::QueryAuthorityTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::QueryControlTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::QueryEventsTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::QueryGeomagneticPropertyTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::QueryGlobalPoseTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::QueryTimeoutTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context, QueryGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context, QueryGlobalPose msg, Receive::Body::ReceiveRec transportData)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context, SetGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context, SetGlobalPose msg, Receive::Body::ReceiveRec transportData)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::ReleaseControlTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::RequestControlTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::SendTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::SetAuthorityTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::SetGeomagneticPropertyTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::SetGlobalPoseTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::TimeoutTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::UpdateEventTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        Default(context);
        return;
    }

    void GlobalPoseSensor_ReceiveFSMState::Default(GlobalPoseSensor_ReceiveFSMContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_NotControlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition(GlobalPoseSensor_ReceiveFSMContext& context, JTS::InternalEvent* ie)
    {
        GlobalPoseSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled"
            << std::endl;
        }

        (context.getState()).Exit(context);
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition(JTS::InternalEvent* ie)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.processNotifications("Receiving_Ready_Controlled", ie);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition(JTS::InternalEvent* ie)"
                    << std::endl;
            }

            context.setState(GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled);
        }
        catch (...)
        {
            context.setState(GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled);
            throw;
        }
        (context.getState()).Entry(context);

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_NotControlled::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context, QueryGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)
    {
        GlobalPoseSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled"
            << std::endl;
        }

        GlobalPoseSensor_ReceiveFSMState& endState = context.getState();

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled::ReceiveTransition(QueryGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.SendAction("ReportGeomagneticProperty", transportData);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled::ReceiveTransition(QueryGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)"
                    << std::endl;
            }

            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_NotControlled::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context, QueryGlobalPose msg, Receive::Body::ReceiveRec transportData)
    {
        GlobalPoseSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled"
            << std::endl;
        }

        GlobalPoseSensor_ReceiveFSMState& endState = context.getState();

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled::ReceiveTransition(QueryGlobalPose msg, Receive::Body::ReceiveRec transportData)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.SendAction("ReportGlobalPose", transportData);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled::ReceiveTransition(QueryGlobalPose msg, Receive::Body::ReceiveRec transportData)"
                    << std::endl;
            }

            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_ReceivingTransition(GlobalPoseSensor_ReceiveFSMContext& context, JTS::InternalEvent* ie)
    {
        GlobalPoseSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled"
            << std::endl;
        }

        (context.getState()).Exit(context);
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_ReceivingTransition(JTS::InternalEvent* ie)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.processNotifications("Receiving_Ready_NotControlled", ie);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_ReceivingTransition(JTS::InternalEvent* ie)"
                    << std::endl;
            }

            context.setState(GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled);
        }
        catch (...)
        {
            context.setState(GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled);
            throw;
        }
        (context.getState()).Entry(context);

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_ReadyTransition(GlobalPoseSensor_ReceiveFSMContext& context, JTS::InternalEvent* ie)
    {
        GlobalPoseSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled"
            << std::endl;
        }

        (context.getState()).Exit(context);
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_ReadyTransition(JTS::InternalEvent* ie)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.processNotifications("Receiving_Ready_NotControlled", ie);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_ReadyTransition(JTS::InternalEvent* ie)"
                    << std::endl;
            }

            context.setState(GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled);
        }
        catch (...)
        {
            context.setState(GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled);
            throw;
        }
        (context.getState()).Entry(context);

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition(GlobalPoseSensor_ReceiveFSMContext& context, JTS::InternalEvent* ie)
    {
        GlobalPoseSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled"
            << std::endl;
        }

        (context.getState()).Exit(context);
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition(JTS::InternalEvent* ie)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.processNotifications("Receiving_Ready_NotControlled", ie);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::InternalStateChange_To_GlobalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition(JTS::InternalEvent* ie)"
                    << std::endl;
            }

            context.setState(GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled);
        }
        catch (...)
        {
            context.setState(GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_NotControlled);
            throw;
        }
        (context.getState()).Entry(context);

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context, QueryGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)
    {
        GlobalPoseSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled"
            << std::endl;
        }

        GlobalPoseSensor_ReceiveFSMState& endState = context.getState();

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::ReceiveTransition(QueryGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.SendAction("ReportGeomagneticProperty", transportData);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::ReceiveTransition(QueryGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)"
                    << std::endl;
            }

            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context, QueryGlobalPose msg, Receive::Body::ReceiveRec transportData)
    {
        GlobalPoseSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled"
            << std::endl;
        }

        GlobalPoseSensor_ReceiveFSMState& endState = context.getState();

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::ReceiveTransition(QueryGlobalPose msg, Receive::Body::ReceiveRec transportData)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.SendAction("ReportGlobalPose", transportData);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::ReceiveTransition(QueryGlobalPose msg, Receive::Body::ReceiveRec transportData)"
                    << std::endl;
            }

            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context, SetGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)
    {
        GlobalPoseSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled"
            << std::endl;
        }

        if (ctxt.isControllingClient( transportData ))
        {
            GlobalPoseSensor_ReceiveFSMState& endState = context.getState();

            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::ReceiveTransition(SetGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)"
                    << std::endl;
            }

            context.clearState();
            try
            {
                ctxt.updateGeomagneticPropertyAction();
                if (context.getDebugFlag() == true)
                {
                    std::ostream& str = context.getDebugStream();

                    str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::ReceiveTransition(SetGeomagneticProperty msg, Receive::Body::ReceiveRec transportData)"
                        << std::endl;
                }

                context.setState(endState);
            }
            catch (...)
            {
                context.setState(endState);
                throw;
            }
        }
        else
        {
             GlobalPoseSensor_ReceiveFSM_SM_Default::ReceiveTransition(context, msg, transportData);
        }

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context, SetGlobalPose msg, Receive::Body::ReceiveRec transportData)
    {
        GlobalPoseSensor_ReceiveFSM& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled"
            << std::endl;
        }

        if (ctxt.isControllingClient( transportData ))
        {
            GlobalPoseSensor_ReceiveFSMState& endState = context.getState();

            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::ReceiveTransition(SetGlobalPose msg, Receive::Body::ReceiveRec transportData)"
                    << std::endl;
            }

            context.clearState();
            try
            {
                ctxt.updateGlobalPoseAction();
                if (context.getDebugFlag() == true)
                {
                    std::ostream& str = context.getDebugStream();

                    str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Receiving_Ready_Controlled::ReceiveTransition(SetGlobalPose msg, Receive::Body::ReceiveRec transportData)"
                        << std::endl;
                }

                context.setState(endState);
            }
            catch (...)
            {
                context.setState(endState);
                throw;
            }
        }
        else
        {
             GlobalPoseSensor_ReceiveFSM_SM_Default::ReceiveTransition(context, msg, transportData);
        }

        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastGlobalTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::BroadcastLocalTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::CancelEventTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::CancelEventTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::CreateEventTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::CreateEventTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::EventErrorTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::EventErrorTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::EventOccurredTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::EventOccurredTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryAuthorityTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryAuthorityTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryAuthorityTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryControlTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryControlTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryControlTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryEventsTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryEventsTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryGeomagneticPropertyTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryGeomagneticPropertyTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryGeomagneticPropertyTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryGlobalPoseTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryGlobalPoseTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryGlobalPoseTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::QueryTimeoutTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryTimeoutTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::QueryTimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::ReceiveTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::ReceiveTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::ReleaseControlTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::ReleaseControlTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::ReleaseControlTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::RequestControlTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::RequestControlTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::RequestControlTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::SendTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::SendTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::SetAuthorityTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::SetAuthorityTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::SetAuthorityTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::SetGeomagneticPropertyTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::SetGeomagneticPropertyTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::SetGeomagneticPropertyTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::SetGlobalPoseTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::SetGlobalPoseTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::SetGlobalPoseTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::TimeoutTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::TimeoutTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::TimeoutTransition()"
                << std::endl;
        }


        return;
    }

    void GlobalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE::UpdateEventTransition(GlobalPoseSensor_ReceiveFSMContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : GlobalPoseSensor_ReceiveFSM_SM::Internally_Generated_State_DO_NOT_USE::UpdateEventTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
