#ifndef _H_GLOBALVECTORDRIVER_SENDFSM_SM
#define _H_GLOBALVECTORDRIVER_SENDFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : GlobalVectorDriver_SendFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_mobility_GlobalVectorDriver_1_0
{
    // Forward declarations.
    class GlobalVectorDriver_SendFSM_SM;
    class GlobalVectorDriver_SendFSM_SM_Sending;
    class GlobalVectorDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class GlobalVectorDriver_SendFSM_SM_Default;
    class GlobalVectorDriver_SendFSMState;
    class GlobalVectorDriver_SendFSMContext;
    class GlobalVectorDriver_SendFSM;

    class GlobalVectorDriver_SendFSMState :
        public statemap::State
    {
    public:

        GlobalVectorDriver_SendFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(GlobalVectorDriver_SendFSMContext&) {};
        virtual void Exit(GlobalVectorDriver_SendFSMContext&) {};

        virtual void BroadcastGlobalTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void BroadcastLocalTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void CancelEventTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void ClearEmergencyTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void CreateEventTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void EventErrorTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void EventOccurredTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void FailureTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void InitializedTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void QueryAuthorityTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void QueryControlTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void QueryEventsTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void QueryGlobalVectorTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void QueryStatusTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void QueryTimeoutTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void ReceiveTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void ReleaseControlTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void RequestControlTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void ResetTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void ResumeTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void SendTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void SetAuthorityTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void SetEmergencyTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void SetGlobalVectorTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void ShutdownTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void StandbyTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void TimeoutTransition(GlobalVectorDriver_SendFSMContext& context);
        virtual void UpdateEventTransition(GlobalVectorDriver_SendFSMContext& context);

    protected:

        virtual void Default(GlobalVectorDriver_SendFSMContext& context);
    };

    class GlobalVectorDriver_SendFSM_SM
    {
    public:

        static GlobalVectorDriver_SendFSM_SM_Sending Sending;
        static GlobalVectorDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class GlobalVectorDriver_SendFSM_SM_Default :
        public GlobalVectorDriver_SendFSMState
    {
    public:

        GlobalVectorDriver_SendFSM_SM_Default(const char *name, int stateId)
        : GlobalVectorDriver_SendFSMState(name, stateId)
        {};

    };

    class GlobalVectorDriver_SendFSM_SM_Sending :
        public GlobalVectorDriver_SendFSM_SM_Default
    {
    public:
        GlobalVectorDriver_SendFSM_SM_Sending(const char *name, int stateId)
        : GlobalVectorDriver_SendFSM_SM_Default(name, stateId)
        {};

    };

    class GlobalVectorDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public GlobalVectorDriver_SendFSM_SM_Default
    {
    public:
        GlobalVectorDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : GlobalVectorDriver_SendFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(GlobalVectorDriver_SendFSMContext& context);
        void BroadcastLocalTransition(GlobalVectorDriver_SendFSMContext& context);
        void CancelEventTransition(GlobalVectorDriver_SendFSMContext& context);
        void ClearEmergencyTransition(GlobalVectorDriver_SendFSMContext& context);
        void CreateEventTransition(GlobalVectorDriver_SendFSMContext& context);
        void EventErrorTransition(GlobalVectorDriver_SendFSMContext& context);
        void EventOccurredTransition(GlobalVectorDriver_SendFSMContext& context);
        void FailureTransition(GlobalVectorDriver_SendFSMContext& context);
        void InitializedTransition(GlobalVectorDriver_SendFSMContext& context);
        void QueryAuthorityTransition(GlobalVectorDriver_SendFSMContext& context);
        void QueryControlTransition(GlobalVectorDriver_SendFSMContext& context);
        void QueryEventsTransition(GlobalVectorDriver_SendFSMContext& context);
        void QueryGlobalVectorTransition(GlobalVectorDriver_SendFSMContext& context);
        void QueryStatusTransition(GlobalVectorDriver_SendFSMContext& context);
        void QueryTimeoutTransition(GlobalVectorDriver_SendFSMContext& context);
        void ReceiveTransition(GlobalVectorDriver_SendFSMContext& context);
        void ReleaseControlTransition(GlobalVectorDriver_SendFSMContext& context);
        void RequestControlTransition(GlobalVectorDriver_SendFSMContext& context);
        void ResetTransition(GlobalVectorDriver_SendFSMContext& context);
        void ResumeTransition(GlobalVectorDriver_SendFSMContext& context);
        void SendTransition(GlobalVectorDriver_SendFSMContext& context);
        void SetAuthorityTransition(GlobalVectorDriver_SendFSMContext& context);
        void SetEmergencyTransition(GlobalVectorDriver_SendFSMContext& context);
        void SetGlobalVectorTransition(GlobalVectorDriver_SendFSMContext& context);
        void ShutdownTransition(GlobalVectorDriver_SendFSMContext& context);
        void StandbyTransition(GlobalVectorDriver_SendFSMContext& context);
        void TimeoutTransition(GlobalVectorDriver_SendFSMContext& context);
        void UpdateEventTransition(GlobalVectorDriver_SendFSMContext& context);
    };

    class GlobalVectorDriver_SendFSMContext :
        public statemap::FSMContext
    {
    public:

        GlobalVectorDriver_SendFSMContext(GlobalVectorDriver_SendFSM& owner)
        : FSMContext(GlobalVectorDriver_SendFSM_SM::Sending),
          _owner(owner)
        {};

        GlobalVectorDriver_SendFSMContext(GlobalVectorDriver_SendFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        GlobalVectorDriver_SendFSM& getOwner() const
        {
            return (_owner);
        };

        GlobalVectorDriver_SendFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<GlobalVectorDriver_SendFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void ClearEmergencyTransition()
        {
            setTransition("ClearEmergencyTransition");
            (getState()).ClearEmergencyTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void FailureTransition()
        {
            setTransition("FailureTransition");
            (getState()).FailureTransition(*this);
            setTransition(NULL);
        };

        void InitializedTransition()
        {
            setTransition("InitializedTransition");
            (getState()).InitializedTransition(*this);
            setTransition(NULL);
        };

        void QueryAuthorityTransition()
        {
            setTransition("QueryAuthorityTransition");
            (getState()).QueryAuthorityTransition(*this);
            setTransition(NULL);
        };

        void QueryControlTransition()
        {
            setTransition("QueryControlTransition");
            (getState()).QueryControlTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void QueryGlobalVectorTransition()
        {
            setTransition("QueryGlobalVectorTransition");
            (getState()).QueryGlobalVectorTransition(*this);
            setTransition(NULL);
        };

        void QueryStatusTransition()
        {
            setTransition("QueryStatusTransition");
            (getState()).QueryStatusTransition(*this);
            setTransition(NULL);
        };

        void QueryTimeoutTransition()
        {
            setTransition("QueryTimeoutTransition");
            (getState()).QueryTimeoutTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void ReleaseControlTransition()
        {
            setTransition("ReleaseControlTransition");
            (getState()).ReleaseControlTransition(*this);
            setTransition(NULL);
        };

        void RequestControlTransition()
        {
            setTransition("RequestControlTransition");
            (getState()).RequestControlTransition(*this);
            setTransition(NULL);
        };

        void ResetTransition()
        {
            setTransition("ResetTransition");
            (getState()).ResetTransition(*this);
            setTransition(NULL);
        };

        void ResumeTransition()
        {
            setTransition("ResumeTransition");
            (getState()).ResumeTransition(*this);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void SetAuthorityTransition()
        {
            setTransition("SetAuthorityTransition");
            (getState()).SetAuthorityTransition(*this);
            setTransition(NULL);
        };

        void SetEmergencyTransition()
        {
            setTransition("SetEmergencyTransition");
            (getState()).SetEmergencyTransition(*this);
            setTransition(NULL);
        };

        void SetGlobalVectorTransition()
        {
            setTransition("SetGlobalVectorTransition");
            (getState()).SetGlobalVectorTransition(*this);
            setTransition(NULL);
        };

        void ShutdownTransition()
        {
            setTransition("ShutdownTransition");
            (getState()).ShutdownTransition(*this);
            setTransition(NULL);
        };

        void StandbyTransition()
        {
            setTransition("StandbyTransition");
            (getState()).StandbyTransition(*this);
            setTransition(NULL);
        };

        void TimeoutTransition()
        {
            setTransition("TimeoutTransition");
            (getState()).TimeoutTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        GlobalVectorDriver_SendFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_GLOBALVECTORDRIVER_SENDFSM_SM
