#ifndef _H_VELOCITYSTATESENSOR_SENDFSM_SM
#define _H_VELOCITYSTATESENSOR_SENDFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : VelocityStateSensor_SendFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_mobility_VelocityStateSensor_1_0
{
    // Forward declarations.
    class VelocityStateSensor_SendFSM_SM;
    class VelocityStateSensor_SendFSM_SM_Sending;
    class VelocityStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class VelocityStateSensor_SendFSM_SM_Default;
    class VelocityStateSensor_SendFSMState;
    class VelocityStateSensor_SendFSMContext;
    class VelocityStateSensor_SendFSM;

    class VelocityStateSensor_SendFSMState :
        public statemap::State
    {
    public:

        VelocityStateSensor_SendFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(VelocityStateSensor_SendFSMContext&) {};
        virtual void Exit(VelocityStateSensor_SendFSMContext&) {};

        virtual void BroadcastGlobalTransition(VelocityStateSensor_SendFSMContext& context);
        virtual void BroadcastLocalTransition(VelocityStateSensor_SendFSMContext& context);
        virtual void CancelEventTransition(VelocityStateSensor_SendFSMContext& context);
        virtual void CreateEventTransition(VelocityStateSensor_SendFSMContext& context);
        virtual void EventErrorTransition(VelocityStateSensor_SendFSMContext& context);
        virtual void EventOccurredTransition(VelocityStateSensor_SendFSMContext& context);
        virtual void QueryEventsTransition(VelocityStateSensor_SendFSMContext& context);
        virtual void QueryVelocityStateTransition(VelocityStateSensor_SendFSMContext& context);
        virtual void ReceiveTransition(VelocityStateSensor_SendFSMContext& context);
        virtual void SendTransition(VelocityStateSensor_SendFSMContext& context);
        virtual void UpdateEventTransition(VelocityStateSensor_SendFSMContext& context);

    protected:

        virtual void Default(VelocityStateSensor_SendFSMContext& context);
    };

    class VelocityStateSensor_SendFSM_SM
    {
    public:

        static VelocityStateSensor_SendFSM_SM_Sending Sending;
        static VelocityStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class VelocityStateSensor_SendFSM_SM_Default :
        public VelocityStateSensor_SendFSMState
    {
    public:

        VelocityStateSensor_SendFSM_SM_Default(const char *name, int stateId)
        : VelocityStateSensor_SendFSMState(name, stateId)
        {};

    };

    class VelocityStateSensor_SendFSM_SM_Sending :
        public VelocityStateSensor_SendFSM_SM_Default
    {
    public:
        VelocityStateSensor_SendFSM_SM_Sending(const char *name, int stateId)
        : VelocityStateSensor_SendFSM_SM_Default(name, stateId)
        {};

    };

    class VelocityStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public VelocityStateSensor_SendFSM_SM_Default
    {
    public:
        VelocityStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : VelocityStateSensor_SendFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(VelocityStateSensor_SendFSMContext& context);
        void BroadcastLocalTransition(VelocityStateSensor_SendFSMContext& context);
        void CancelEventTransition(VelocityStateSensor_SendFSMContext& context);
        void CreateEventTransition(VelocityStateSensor_SendFSMContext& context);
        void EventErrorTransition(VelocityStateSensor_SendFSMContext& context);
        void EventOccurredTransition(VelocityStateSensor_SendFSMContext& context);
        void QueryEventsTransition(VelocityStateSensor_SendFSMContext& context);
        void QueryVelocityStateTransition(VelocityStateSensor_SendFSMContext& context);
        void ReceiveTransition(VelocityStateSensor_SendFSMContext& context);
        void SendTransition(VelocityStateSensor_SendFSMContext& context);
        void UpdateEventTransition(VelocityStateSensor_SendFSMContext& context);
    };

    class VelocityStateSensor_SendFSMContext :
        public statemap::FSMContext
    {
    public:

        VelocityStateSensor_SendFSMContext(VelocityStateSensor_SendFSM& owner)
        : FSMContext(VelocityStateSensor_SendFSM_SM::Sending),
          _owner(owner)
        {};

        VelocityStateSensor_SendFSMContext(VelocityStateSensor_SendFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        VelocityStateSensor_SendFSM& getOwner() const
        {
            return (_owner);
        };

        VelocityStateSensor_SendFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<VelocityStateSensor_SendFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void QueryVelocityStateTransition()
        {
            setTransition("QueryVelocityStateTransition");
            (getState()).QueryVelocityStateTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        VelocityStateSensor_SendFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_VELOCITYSTATESENSOR_SENDFSM_SM
