#ifndef _H_GLOBALPOSESENSOR_SENDFSM_SM
#define _H_GLOBALPOSESENSOR_SENDFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : GlobalPoseSensor_SendFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_mobility_GlobalPoseSensor_1_0
{
    // Forward declarations.
    class GlobalPoseSensor_SendFSM_SM;
    class GlobalPoseSensor_SendFSM_SM_Sending;
    class GlobalPoseSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class GlobalPoseSensor_SendFSM_SM_Default;
    class GlobalPoseSensor_SendFSMState;
    class GlobalPoseSensor_SendFSMContext;
    class GlobalPoseSensor_SendFSM;

    class GlobalPoseSensor_SendFSMState :
        public statemap::State
    {
    public:

        GlobalPoseSensor_SendFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(GlobalPoseSensor_SendFSMContext&) {};
        virtual void Exit(GlobalPoseSensor_SendFSMContext&) {};

        virtual void BroadcastGlobalTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void BroadcastLocalTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void CancelEventTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void CreateEventTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void EventErrorTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void EventOccurredTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void QueryAuthorityTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void QueryControlTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void QueryEventsTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void QueryGeomagneticPropertyTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void QueryGlobalPoseTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void QueryTimeoutTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void ReceiveTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void ReleaseControlTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void RequestControlTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void SendTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void SetAuthorityTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void SetGeomagneticPropertyTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void SetGlobalPoseTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void TimeoutTransition(GlobalPoseSensor_SendFSMContext& context);
        virtual void UpdateEventTransition(GlobalPoseSensor_SendFSMContext& context);

    protected:

        virtual void Default(GlobalPoseSensor_SendFSMContext& context);
    };

    class GlobalPoseSensor_SendFSM_SM
    {
    public:

        static GlobalPoseSensor_SendFSM_SM_Sending Sending;
        static GlobalPoseSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class GlobalPoseSensor_SendFSM_SM_Default :
        public GlobalPoseSensor_SendFSMState
    {
    public:

        GlobalPoseSensor_SendFSM_SM_Default(const char *name, int stateId)
        : GlobalPoseSensor_SendFSMState(name, stateId)
        {};

    };

    class GlobalPoseSensor_SendFSM_SM_Sending :
        public GlobalPoseSensor_SendFSM_SM_Default
    {
    public:
        GlobalPoseSensor_SendFSM_SM_Sending(const char *name, int stateId)
        : GlobalPoseSensor_SendFSM_SM_Default(name, stateId)
        {};

    };

    class GlobalPoseSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public GlobalPoseSensor_SendFSM_SM_Default
    {
    public:
        GlobalPoseSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : GlobalPoseSensor_SendFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(GlobalPoseSensor_SendFSMContext& context);
        void BroadcastLocalTransition(GlobalPoseSensor_SendFSMContext& context);
        void CancelEventTransition(GlobalPoseSensor_SendFSMContext& context);
        void CreateEventTransition(GlobalPoseSensor_SendFSMContext& context);
        void EventErrorTransition(GlobalPoseSensor_SendFSMContext& context);
        void EventOccurredTransition(GlobalPoseSensor_SendFSMContext& context);
        void QueryAuthorityTransition(GlobalPoseSensor_SendFSMContext& context);
        void QueryControlTransition(GlobalPoseSensor_SendFSMContext& context);
        void QueryEventsTransition(GlobalPoseSensor_SendFSMContext& context);
        void QueryGeomagneticPropertyTransition(GlobalPoseSensor_SendFSMContext& context);
        void QueryGlobalPoseTransition(GlobalPoseSensor_SendFSMContext& context);
        void QueryTimeoutTransition(GlobalPoseSensor_SendFSMContext& context);
        void ReceiveTransition(GlobalPoseSensor_SendFSMContext& context);
        void ReleaseControlTransition(GlobalPoseSensor_SendFSMContext& context);
        void RequestControlTransition(GlobalPoseSensor_SendFSMContext& context);
        void SendTransition(GlobalPoseSensor_SendFSMContext& context);
        void SetAuthorityTransition(GlobalPoseSensor_SendFSMContext& context);
        void SetGeomagneticPropertyTransition(GlobalPoseSensor_SendFSMContext& context);
        void SetGlobalPoseTransition(GlobalPoseSensor_SendFSMContext& context);
        void TimeoutTransition(GlobalPoseSensor_SendFSMContext& context);
        void UpdateEventTransition(GlobalPoseSensor_SendFSMContext& context);
    };

    class GlobalPoseSensor_SendFSMContext :
        public statemap::FSMContext
    {
    public:

        GlobalPoseSensor_SendFSMContext(GlobalPoseSensor_SendFSM& owner)
        : FSMContext(GlobalPoseSensor_SendFSM_SM::Sending),
          _owner(owner)
        {};

        GlobalPoseSensor_SendFSMContext(GlobalPoseSensor_SendFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        GlobalPoseSensor_SendFSM& getOwner() const
        {
            return (_owner);
        };

        GlobalPoseSensor_SendFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<GlobalPoseSensor_SendFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void QueryAuthorityTransition()
        {
            setTransition("QueryAuthorityTransition");
            (getState()).QueryAuthorityTransition(*this);
            setTransition(NULL);
        };

        void QueryControlTransition()
        {
            setTransition("QueryControlTransition");
            (getState()).QueryControlTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void QueryGeomagneticPropertyTransition()
        {
            setTransition("QueryGeomagneticPropertyTransition");
            (getState()).QueryGeomagneticPropertyTransition(*this);
            setTransition(NULL);
        };

        void QueryGlobalPoseTransition()
        {
            setTransition("QueryGlobalPoseTransition");
            (getState()).QueryGlobalPoseTransition(*this);
            setTransition(NULL);
        };

        void QueryTimeoutTransition()
        {
            setTransition("QueryTimeoutTransition");
            (getState()).QueryTimeoutTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void ReleaseControlTransition()
        {
            setTransition("ReleaseControlTransition");
            (getState()).ReleaseControlTransition(*this);
            setTransition(NULL);
        };

        void RequestControlTransition()
        {
            setTransition("RequestControlTransition");
            (getState()).RequestControlTransition(*this);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void SetAuthorityTransition()
        {
            setTransition("SetAuthorityTransition");
            (getState()).SetAuthorityTransition(*this);
            setTransition(NULL);
        };

        void SetGeomagneticPropertyTransition()
        {
            setTransition("SetGeomagneticPropertyTransition");
            (getState()).SetGeomagneticPropertyTransition(*this);
            setTransition(NULL);
        };

        void SetGlobalPoseTransition()
        {
            setTransition("SetGlobalPoseTransition");
            (getState()).SetGlobalPoseTransition(*this);
            setTransition(NULL);
        };

        void TimeoutTransition()
        {
            setTransition("TimeoutTransition");
            (getState()).TimeoutTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        GlobalPoseSensor_SendFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_GLOBALPOSESENSOR_SENDFSM_SM
