#ifndef _H_ACCELERATIONSTATESENSOR_RECEIVEFSM_SM
#define _H_ACCELERATIONSTATESENSOR_RECEIVEFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AccelerationStateSensor_ReceiveFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_mobility_AccelerationStateSensor_0_6
{
    // Forward declarations.
    class AccelerationStateSensor_ReceiveFSM_SM;
    class AccelerationStateSensor_ReceiveFSM_SM_Receiving_Ready;
    class AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class AccelerationStateSensor_ReceiveFSM_SM_Default;
    class AccelerationStateSensor_ReceiveFSMState;
    class AccelerationStateSensor_ReceiveFSMContext;
    class AccelerationStateSensor_ReceiveFSM;

    class AccelerationStateSensor_ReceiveFSMState :
        public statemap::State
    {
    public:

        AccelerationStateSensor_ReceiveFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(AccelerationStateSensor_ReceiveFSMContext&) {};
        virtual void Exit(AccelerationStateSensor_ReceiveFSMContext&) {};

        virtual void BroadcastGlobalTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        virtual void BroadcastLocalTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        virtual void CancelEventTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        virtual void CreateEventTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        virtual void EventErrorTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        virtual void EventOccurredTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        virtual void QueryAccelerationStateTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        virtual void QueryEventsTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        virtual void ReceiveTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        virtual void ReceiveTransition(AccelerationStateSensor_ReceiveFSMContext& context, QueryAccelerationState msg, Receive::Body::ReceiveRec transportData);
        virtual void SendTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        virtual void UpdateEventTransition(AccelerationStateSensor_ReceiveFSMContext& context);

    protected:

        virtual void Default(AccelerationStateSensor_ReceiveFSMContext& context);
    };

    class AccelerationStateSensor_ReceiveFSM_SM
    {
    public:

        static AccelerationStateSensor_ReceiveFSM_SM_Receiving_Ready Receiving_Ready;
        static AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class AccelerationStateSensor_ReceiveFSM_SM_Default :
        public AccelerationStateSensor_ReceiveFSMState
    {
    public:

        AccelerationStateSensor_ReceiveFSM_SM_Default(const char *name, int stateId)
        : AccelerationStateSensor_ReceiveFSMState(name, stateId)
        {};

    };

    class AccelerationStateSensor_ReceiveFSM_SM_Receiving_Ready :
        public AccelerationStateSensor_ReceiveFSM_SM_Default
    {
    public:
        AccelerationStateSensor_ReceiveFSM_SM_Receiving_Ready(const char *name, int stateId)
        : AccelerationStateSensor_ReceiveFSM_SM_Default(name, stateId)
        {};

        void ReceiveTransition(AccelerationStateSensor_ReceiveFSMContext& context, QueryAccelerationState msg, Receive::Body::ReceiveRec transportData);
    };

    class AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public AccelerationStateSensor_ReceiveFSM_SM_Default
    {
    public:
        AccelerationStateSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : AccelerationStateSensor_ReceiveFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        void BroadcastLocalTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        void CancelEventTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        void CreateEventTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        void EventErrorTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        void EventOccurredTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        void QueryAccelerationStateTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        void QueryEventsTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        void ReceiveTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        void SendTransition(AccelerationStateSensor_ReceiveFSMContext& context);
        void UpdateEventTransition(AccelerationStateSensor_ReceiveFSMContext& context);
    };

    class AccelerationStateSensor_ReceiveFSMContext :
        public statemap::FSMContext
    {
    public:

        AccelerationStateSensor_ReceiveFSMContext(AccelerationStateSensor_ReceiveFSM& owner)
        : FSMContext(AccelerationStateSensor_ReceiveFSM_SM::Receiving_Ready),
          _owner(owner)
        {};

        AccelerationStateSensor_ReceiveFSMContext(AccelerationStateSensor_ReceiveFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        AccelerationStateSensor_ReceiveFSM& getOwner() const
        {
            return (_owner);
        };

        AccelerationStateSensor_ReceiveFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<AccelerationStateSensor_ReceiveFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void QueryAccelerationStateTransition()
        {
            setTransition("QueryAccelerationStateTransition");
            (getState()).QueryAccelerationStateTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition(QueryAccelerationState msg, Receive::Body::ReceiveRec transportData)
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this, msg, transportData);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        AccelerationStateSensor_ReceiveFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_ACCELERATIONSTATESENSOR_RECEIVEFSM_SM
