#ifndef _H_ACCELERATIONSTATESENSOR_SENDFSM_SM
#define _H_ACCELERATIONSTATESENSOR_SENDFSM_SM

/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AccelerationStateSensor_SendFSM_sm.sm
 */


#define SMC_USES_IOSTREAMS

#include <statemap.h>

namespace urn_jaus_jss_mobility_AccelerationStateSensor_0_6
{
    // Forward declarations.
    class AccelerationStateSensor_SendFSM_SM;
    class AccelerationStateSensor_SendFSM_SM_Sending;
    class AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE;
    class AccelerationStateSensor_SendFSM_SM_Default;
    class AccelerationStateSensor_SendFSMState;
    class AccelerationStateSensor_SendFSMContext;
    class AccelerationStateSensor_SendFSM;

    class AccelerationStateSensor_SendFSMState :
        public statemap::State
    {
    public:

        AccelerationStateSensor_SendFSMState(const char *name, int stateId)
        : statemap::State(name, stateId)
        {};

        virtual void Entry(AccelerationStateSensor_SendFSMContext&) {};
        virtual void Exit(AccelerationStateSensor_SendFSMContext&) {};

        virtual void BroadcastGlobalTransition(AccelerationStateSensor_SendFSMContext& context);
        virtual void BroadcastLocalTransition(AccelerationStateSensor_SendFSMContext& context);
        virtual void CancelEventTransition(AccelerationStateSensor_SendFSMContext& context);
        virtual void CreateEventTransition(AccelerationStateSensor_SendFSMContext& context);
        virtual void EventErrorTransition(AccelerationStateSensor_SendFSMContext& context);
        virtual void EventOccurredTransition(AccelerationStateSensor_SendFSMContext& context);
        virtual void QueryAccelerationStateTransition(AccelerationStateSensor_SendFSMContext& context);
        virtual void QueryEventsTransition(AccelerationStateSensor_SendFSMContext& context);
        virtual void ReceiveTransition(AccelerationStateSensor_SendFSMContext& context);
        virtual void SendTransition(AccelerationStateSensor_SendFSMContext& context);
        virtual void UpdateEventTransition(AccelerationStateSensor_SendFSMContext& context);

    protected:

        virtual void Default(AccelerationStateSensor_SendFSMContext& context);
    };

    class AccelerationStateSensor_SendFSM_SM
    {
    public:

        static AccelerationStateSensor_SendFSM_SM_Sending Sending;
        static AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE;
    };

    class AccelerationStateSensor_SendFSM_SM_Default :
        public AccelerationStateSensor_SendFSMState
    {
    public:

        AccelerationStateSensor_SendFSM_SM_Default(const char *name, int stateId)
        : AccelerationStateSensor_SendFSMState(name, stateId)
        {};

    };

    class AccelerationStateSensor_SendFSM_SM_Sending :
        public AccelerationStateSensor_SendFSM_SM_Default
    {
    public:
        AccelerationStateSensor_SendFSM_SM_Sending(const char *name, int stateId)
        : AccelerationStateSensor_SendFSM_SM_Default(name, stateId)
        {};

    };

    class AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE :
        public AccelerationStateSensor_SendFSM_SM_Default
    {
    public:
        AccelerationStateSensor_SendFSM_SM_Internally_Generated_State_DO_NOT_USE(const char *name, int stateId)
        : AccelerationStateSensor_SendFSM_SM_Default(name, stateId)
        {};

        void BroadcastGlobalTransition(AccelerationStateSensor_SendFSMContext& context);
        void BroadcastLocalTransition(AccelerationStateSensor_SendFSMContext& context);
        void CancelEventTransition(AccelerationStateSensor_SendFSMContext& context);
        void CreateEventTransition(AccelerationStateSensor_SendFSMContext& context);
        void EventErrorTransition(AccelerationStateSensor_SendFSMContext& context);
        void EventOccurredTransition(AccelerationStateSensor_SendFSMContext& context);
        void QueryAccelerationStateTransition(AccelerationStateSensor_SendFSMContext& context);
        void QueryEventsTransition(AccelerationStateSensor_SendFSMContext& context);
        void ReceiveTransition(AccelerationStateSensor_SendFSMContext& context);
        void SendTransition(AccelerationStateSensor_SendFSMContext& context);
        void UpdateEventTransition(AccelerationStateSensor_SendFSMContext& context);
    };

    class AccelerationStateSensor_SendFSMContext :
        public statemap::FSMContext
    {
    public:

        AccelerationStateSensor_SendFSMContext(AccelerationStateSensor_SendFSM& owner)
        : FSMContext(AccelerationStateSensor_SendFSM_SM::Sending),
          _owner(owner)
        {};

        AccelerationStateSensor_SendFSMContext(AccelerationStateSensor_SendFSM& owner, const statemap::State& state)
        : FSMContext(state),
          _owner(owner)
        {};

        virtual void enterStartState()
        {
            getState().Entry(*this);
            return;
        }

        AccelerationStateSensor_SendFSM& getOwner() const
        {
            return (_owner);
        };

        AccelerationStateSensor_SendFSMState& getState() const
        {
            if (_state == NULL)
            {
                throw statemap::StateUndefinedException();
            }

            return (dynamic_cast<AccelerationStateSensor_SendFSMState&>(*_state));
        };

        void BroadcastGlobalTransition()
        {
            setTransition("BroadcastGlobalTransition");
            (getState()).BroadcastGlobalTransition(*this);
            setTransition(NULL);
        };

        void BroadcastLocalTransition()
        {
            setTransition("BroadcastLocalTransition");
            (getState()).BroadcastLocalTransition(*this);
            setTransition(NULL);
        };

        void CancelEventTransition()
        {
            setTransition("CancelEventTransition");
            (getState()).CancelEventTransition(*this);
            setTransition(NULL);
        };

        void CreateEventTransition()
        {
            setTransition("CreateEventTransition");
            (getState()).CreateEventTransition(*this);
            setTransition(NULL);
        };

        void EventErrorTransition()
        {
            setTransition("EventErrorTransition");
            (getState()).EventErrorTransition(*this);
            setTransition(NULL);
        };

        void EventOccurredTransition()
        {
            setTransition("EventOccurredTransition");
            (getState()).EventOccurredTransition(*this);
            setTransition(NULL);
        };

        void QueryAccelerationStateTransition()
        {
            setTransition("QueryAccelerationStateTransition");
            (getState()).QueryAccelerationStateTransition(*this);
            setTransition(NULL);
        };

        void QueryEventsTransition()
        {
            setTransition("QueryEventsTransition");
            (getState()).QueryEventsTransition(*this);
            setTransition(NULL);
        };

        void ReceiveTransition()
        {
            setTransition("ReceiveTransition");
            (getState()).ReceiveTransition(*this);
            setTransition(NULL);
        };

        void SendTransition()
        {
            setTransition("SendTransition");
            (getState()).SendTransition(*this);
            setTransition(NULL);
        };

        void UpdateEventTransition()
        {
            setTransition("UpdateEventTransition");
            (getState()).UpdateEventTransition(*this);
            setTransition(NULL);
        };

    private:

        AccelerationStateSensor_SendFSM& _owner;
    };
}


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */

#endif // _H_ACCELERATIONSTATESENSOR_SENDFSM_SM
